### PR TITLE
function test doesn't seem right to me.

### PR DESCRIPTION
**Pull request by stevemao**
`Object.assign` would be the same.

### CODE REVIEW

**Comment by schnittstabil** [comment]
Aww yeah, that looks strange at first glance. However, the important part is this:

``` js
const oracle42 = () => 42;
const oracle666 = () => 666;
oracle42.foo = true;
// ...
const target = fn({}, {oracle: oracle42}, {oracle: oracle666});
// ...
t.is(target.oracle.foo, true); // <--- here!
```

I'm fine with: 

``` diff
-   t.is(target.oracle(), 42);
+   t.is(target.oracle(), 666);
```

I think both versions match the project description. However, IMO `target.oracle.foo` have to be `true`, because:

``` js
const oracle42 = {};
const oracle666 = {};
oracle42.foo = true;
// ...
const target = fn({}, {oracle: oracle42}, {oracle: oracle666});
// ...
t.is(target.oracle.foo, true); // <--- here!
```

**Comment by sshcxcx** [comment]
my code is:

``` js
var a = {
  xAxis: [{
    axisLabel: {
      formatter: function (val) {
        return val
      }
    }
  }]
}
var b = deepAssign({}, a, {
  xAxis: [{
    axisLabel: {
      formatter: function (val) {
        return val.split("").join("\n");
      }
    }
  }]
})
console.log(b.xAxis[0].axisLabel.formatter);
```

Why didn't the object formatter of the b be replaced ?

**EDIT by @schnittstabil:** syntax highlighting added.

**Comment by schnittstabil** [comment]
@sshcxcx `deep-assign` behaves as:

``` js
deepAssign({}, a, {…})
// => …
// =>
{
  xAxis: [{
    axisLabel: {
      formatter: deepAssign(a.xAxis[0].axisLabel.formatter, function (val) {…})
    }
  }]
}
// =>
{
  xAxis: [{
    axisLabel: {
      formatter: Object.assign(a.xAxis[0].axisLabel.formatter, function (val) {…})
    }
  }]
}
```

Please note:

``` js
Object.assign(
  function (val) { return val },
  function (val) { return val.split("").join("\n"); }
)
// => function (val) { return val }
```

There are many merge tools doing this in a different way. Some examples at runkit.com using your code:
- [deep-assign](https://runkit.com/schnittstabil/deep-assign-19-deepassign)
- [_.merge](https://runkit.com/schnittstabil/deep-assign-19-lodash)
- [merge-options](https://runkit.com/schnittstabil/deep-assign-19-mergeoptions) – disclaimer: I'm the author of [`merge-options`](https://github.com/schnittstabil/merge-options)

**Comment by sindresorhus** [comment]
This module is now deprecated: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97

**Pull request closed without merging**
