### PR TITLE
Fixed #6 (reuses object in deep assignment)

### LINKED ISSUE #6: Regression in 2.0.0
This commit https://github.com/sindresorhus/deep-assign/commit/b55d7b6691c83e7ad751452b9e04aadfe718c702 seems to cause problem in [XO](https://github.com/sindresorhus/xo/commit/35aaec846e6858c5c70e1ffdfa0c78f43037a85d).

I've added a failing test: https://github.com/sindresorhus/deep-assign/commit/efa61abbee1593fdfa1ce619017f507ebc7d405c

It seems at deep level it no longer creates a new object but reuses the existing one.

@schnittstabil Could you take a look?

### PR DESCRIPTION
**Pull request by Kreozot**

### CODE REVIEW

**Comment by Kreozot** [comment]
@sindresorhus, I draw your attention that "support symbols as targets" check was failed before this change (when I ran tests just after cloning and now on master branch).

**Comment by schnittstabil** [comment]
@Kreozot Thank you for your suggestion, but I think it is incompatible with the project description of `deep-assign`:

> Recursive Object.assign()

That is because `Object.assign()` does not distinguish plain and non-plain objects, which is the reason I've created [merge-options](https://github.com/schnittstabil/merge-options).

**Comment by Kreozot** [comment]
Sorry, but I don't get it. How do you think deep-assign should behave with internal objects? Because without this PR it acts like simple object-assign.

@sindresorhus, what do you say?

**Comment by schnittstabil** [comment]
@Kreozot It does not. Think of the following snippet already mentioned in #6:

``` js
function User(name) {
  this.name = name;
}

var target = {
    user: new User('Alice')
};

var source = {
    user: new User('Bob')
};

// target.user exists, so deep-assign steps into target.user and source.user:
deepAssign(target, source);
//=> target.user.name === source.user.name === 'Bob'
```

This shows that the  _target object tree_ is recursively updated with properties of `source`, i.e.:

``` js
target.user.name = source.user.name;
// but: target.user !== source.user
```

With non-recursive `Object.assign`:

``` js
Object.assign(target, source);
//=> target.user === source.user
```

**Comment by Kreozot** [comment]
Yes. But with this bug it acts exactly like this. When you assign _fixture.foo.bar_ it actually assign only _fixture.foo_ (that's why changing _bar_ affects original object)

**Comment by schnittstabil** [comment]
@Kreozot With the last example I just wanted to show that `deepAssign` does not act exactly like `Object.assign`, and that it is recursive.

**Comment by Kreozot** [comment]
That's why I said "...with this bug..."
This PR makes deep-assign works as you showed in your example.

**Comment by schnittstabil** [comment]
@Kreozot I thought my (deleted) example was flawed by itself (the output doesn't match the code and I couldn't have recognized any difference).

Took me some time to find some real difference:

``` js
var alice = {};
Object.defineProperty(alice, 'name', {value: 'Alice'});

var result = deepAssign({}, {user: alice});
//Current => result.user.name === 'Alice'
//PR      => result.user.name === undefined
```

Personally I would prefer the current behavior, because it is consistent with non-plain objects:

``` js
function User() {}
var alice = new User();
Object.defineProperty(alice, 'name', {value: 'Alice'});

var result = deepAssign({}, {user: alice});
//Current => result.user.name === 'Alice'
//PR      => result.user.name === 'Alice'
```

In addition, also the [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign) does not distinguish plain and non-plain objects.

**Comment by Kreozot** [comment]
Finally got it. Thanks for the explanation. Will think.

**Comment by Kreozot** [comment]
Sooo... The problem is not in the PR. The problem is in `for (var key in from) {` statement. If you change your property definition to this 
`Object.defineProperty(alice, 'name', {value: 'Alice', enumerable: true});` 
it will be completely allright.

**Comment by schnittstabil** [comment]
@Kreozot exactly, the `enumerable` makes the difference.

> The problem is not in the PR

How you look at it: Your PR introduces the _inconsistenties_ between plain and non-plain objects I've mentioned.

**Comment by Kreozot** [comment]
But the whole point of object assign is that it clone object instead of copying a pointer. Without the PR this is useless at all. I can't be sure that object, from that I assign, is safe.

**Comment by Kreozot** [comment]
Maybe we should create another issue about this problem (and a test for it of course)?

**Comment by schnittstabil** [comment]
> But the whole point of object assign is that it clone object

I don't think so.
1. from [19.1.2.1 Object.assign ( target, ...sources )](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign):
   
   > 1. c. 3. Let status be Set(to, nextKey, propValue, true).
   
   There is no _cloning_ mentioned, only setting, especially ToObject (i.e. `Object()`) does not clone:
   
   ``` js
   var obj = {};
   var objRef = obj;
   obj = Object(obj);
   //=> objRef === obj
   ```
2. all properties are _assigned_ to `target`, i.e. neither `target` nor the sources are cloned:
   
   ``` js
   var target = {};
   var targetRef = target;
   Object.assign(target, {foo: 1});
   target = Object.assign(target, {bar: 2});
   //=> targetRef === target
   ```
3. in most cases cloning is not possible (in a reasonable way), e.g.
   
   ``` js
   function target(n) {
     return true;
   }
   function source(n) {
     return n % 2;
   }
   Object.assign(target, source);
   //=> target !== source
   
   target(0) //=> true
   target(1) //=> true
   ```

> I can't be sure that object, from that I assign, is safe.

Sometimes it is intended not to clone and share references.

**Comment by Kreozot** [comment]
If we talk about object-assign, I agree. But isn't deep-assign do the same but for all nested properties?

**Comment by alexykot** [comment]
I support @Kreozot in here. I've installed deep-assign for this very reason to recursively copy an object, but found it not working as expected. I will have to use his fork instead.

**Comment by stevemao** [comment]
We need to defined what "Recursive Object.assign()" really means here. And I think @Kreozot is more intuitive.

**Comment by sindresorhus** [comment]
This module is now deprecated: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97

**Pull request closed without merging**
